@host=https://192.168.2.61:5001


# @name compactGames
GET {{host}}/api/games

###

# @name categories
# GET {{host}}/api/games/{{compactGames.response.body.0.id}}/categories
GET {{host}}/api/games/mc/categories

###

# @name leaderboard
GET {{host}}/api/leaderboards/{{compactGames.response.body.0.id}}/{{categories.response.body.0.id}}/

###
GET {{host}}/api/tournament

